const DOUBAO_NODE_STUDIO_EXTRACTOR_BUILD = '0.5.6';
if (window.__doubaoNodeStudioExtractorInjected !== DOUBAO_NODE_STUDIO_EXTRACTOR_BUILD) {
window.__doubaoNodeStudioExtractorInjected = DOUBAO_NODE_STUDIO_EXTRACTOR_BUILD;
document.documentElement.dataset.doubaoNodeStudioExtractor = DOUBAO_NODE_STUDIO_EXTRACTOR_BUILD;
window.postMessage({ type:'DOUBAO_NODE_STUDIO_EXTRACTOR_READY', build:DOUBAO_NODE_STUDIO_EXTRACTOR_BUILD }, location.origin);
(() => {
  const MESSAGE = 'DOUBAO_NODE_STUDIO_EXTRACT_MEDIA';
  const RESULT = 'DOUBAO_NODE_STUDIO_MEDIA_RESULT';
  const STATUS_REQUEST = 'DOUBAO_NODE_STUDIO_MEDIA_STATUS_REQUEST';
  const STATUS_RESULT = 'DOUBAO_NODE_STUDIO_MEDIA_STATUS_RESULT';
  const MEDIA_CANDIDATE = 'DOUBAO_NODE_STUDIO_MEDIA_CANDIDATE';
  const BACKGROUND_FETCH_REQUEST = 'DOUBAO_NODE_STUDIO_MEDIA_FETCH_REQUEST';
  const BACKGROUND_FETCH_RESULT = 'DOUBAO_NODE_STUDIO_MEDIA_FETCH_RESULT';
  const fallbackApis = new Set();
  const observedEndpoints = new Set();
  let lastResolveStage = '等待捕获媒体接口';
  let lastResolveError = '';
  let lastFallbackHost = '';
  const QAAB_SALT_HEX = '4dd4c2e6b83162090e52b3c7a6733ba41cb2462b829ab58a196b39db57177524f49baf7f08e8d68d26a72e37c1a95a2f1f05a51892aef2949732b62a38aadd58';
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const isHttpUrl = (value) => typeof value === 'string' && /^https?:\/\//i.test(value);
  const normalizeUrl = (value) => String(value || '').replace(/&amp;/g, '&').replace(/^http:\/\//i, 'https://');
  const publishDebug = () => { document.documentElement.dataset.doubaoNodeStudioFallbackCount = String(fallbackApis.size); document.documentElement.dataset.doubaoNodeStudioResponseCount = String(observedEndpoints.size); document.documentElement.dataset.doubaoNodeStudioResolveStage = lastResolveStage; document.documentElement.dataset.doubaoNodeStudioResolveError = lastResolveError; document.documentElement.dataset.doubaoNodeStudioFallbackHost = lastFallbackHost; };
  publishDebug();

  function backgroundJson(url) { const requestId = crypto.randomUUID(); return new Promise((resolve, reject) => { const timer = setTimeout(() => { window.removeEventListener('message', listener); reject(new Error('后台媒体解析超时')); }, 12000); const listener = (event) => { if (event.source !== window || event.data?.type !== BACKGROUND_FETCH_RESULT || event.data.requestId !== requestId) return; clearTimeout(timer); window.removeEventListener('message', listener); if (!event.data.response?.ok) reject(new Error(event.data.response?.error || '后台媒体解析失败')); else resolve(event.data.response.data); }; window.addEventListener('message', listener); window.postMessage({ type:BACKGROUND_FETCH_REQUEST, requestId, url }, location.origin); }); }

  function decodeEscaped(value) { let text = String(value || ''); for (let i = 0; i < 3; i += 1) { try { const decoded = JSON.parse(`"${text.replace(/"/g, '\\"')}"`); if (decoded === text) break; text = decoded; } catch { break; } } return text.replace(/\\u0026/g, '&').replace(/\\\//g, '/'); }
  function collectFallbackApis(value, raw = '') {
    const before = fallbackApis.size;
    const visit = (item, seen = new WeakSet()) => {
      if (!item) return;
      if (typeof item === 'string') { const text = decodeEscaped(item); try { visit(JSON.parse(text), seen); } catch {} return; }
      if (typeof item !== 'object' || seen.has(item)) return; seen.add(item);
      if (typeof item.fallback_api === 'string' && isHttpUrl(decodeEscaped(item.fallback_api))) fallbackApis.add(decodeEscaped(item.fallback_api));
      Object.values(item).forEach((child) => visit(child, seen));
    };
    visit(value); const source = String(raw || ''); const patterns = [/fallback_api\\":\\"(.*?)\\"/g, /"fallback_api"\s*:\s*"([^"]+)"/g];
    patterns.forEach((pattern) => { let hit; while ((hit = pattern.exec(source))) { const url = decodeEscaped(hit[1]); if (isHttpUrl(url)) fallbackApis.add(url); } }); if (fallbackApis.size > before) { try { lastFallbackHost = new URL([...fallbackApis].at(-1)).hostname; } catch {} lastResolveStage = '已捕获媒体接口，等待解析'; lastResolveError = ''; } publishDebug(); if (fallbackApis.size > before) window.postMessage({ type:MEDIA_CANDIDATE, fallbackCount:fallbackApis.size }, location.origin);
  }
  function scanRenderedMediaData() { const seen = new WeakSet(), queue = []; document.querySelectorAll('video').forEach((video) => { for (let node = video; node && node !== document.body; node = node.parentElement) Object.keys(node).filter((key) => /^__react(?:Props|Fiber|InternalInstance)/.test(key)).forEach((key) => queue.push({ value:node[key], depth:0 })); }); let visited = 0; while (queue.length && visited < 900) { const { value, depth } = queue.shift(); if (!value || typeof value !== 'object' || seen.has(value) || depth > 9) continue; seen.add(value); visited += 1; if (typeof value.fallback_api === 'string' && isHttpUrl(decodeEscaped(value.fallback_api))) fallbackApis.add(decodeEscaped(value.fallback_api)); for (const key of ['props','memoizedProps','pendingProps','video','creation','children','child','return','memoizedState']) if (value[key]) queue.push({ value:value[key], depth:depth + 1 }); } }
  function videoIds(value, output = new Set(), seen = new WeakSet()) { if (!value || typeof value !== 'object') return output; if (seen.has(value)) return output; seen.add(value); for (const key of ['vid', 'video_id', 'videoId']) { const candidate = value[key]; if (typeof candidate === 'string' || typeof candidate === 'number') output.add(String(candidate)); } if (value.video && typeof value.video === 'object') for (const key of ['vid', 'video_id', 'videoId', 'id']) { const candidate = value.video[key]; if (typeof candidate === 'string' || typeof candidate === 'number') output.add(String(candidate)); } Object.values(value).forEach((item) => videoIds(item, output, seen)); return output; }
  function padBase64(text) { return text + '='.repeat((4 - text.length % 4) % 4); }
  function base64DecodeLoose(value) { const input = String(value || '').trim(); for (const item of [input, input.replace(/[$@#]/g, (c) => ({ '$':'_', '@':'/', '#':'.' }[c])), input.replace(/[$@#]/g, (c) => ({ '$':'+', '@':'/', '#':'=' }[c]))]) { try { const binary = atob(padBase64(item).replace(/-/g, '+').replace(/_/g, '/')); return Uint8Array.from(binary, (char) => char.charCodeAt(0)); } catch {} } return null; }
  function asciiUrl(bytes) { if (!bytes?.length || [...bytes].some((byte) => byte !== 9 && byte !== 10 && byte !== 13 && (byte < 32 || byte > 126))) return ''; const value = new TextDecoder().decode(bytes); return isHttpUrl(value) ? value : ''; }
  function hexBytes(hex) { return Uint8Array.from({ length:hex.length / 2 }, (_, index) => Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16)); }
  function concat(first, second) { const output = new Uint8Array(first.length + second.length); output.set(first); output.set(second, first.length); return output; }
  function stripPkcs7(bytes) { const pad = bytes?.[bytes.length - 1]; if (!pad || pad > 16 || pad > bytes.length || [...bytes.slice(bytes.length - pad)].some((byte) => byte !== pad)) return bytes; return bytes.slice(0, bytes.length - pad); }
  async function decryptUrl(payload, keyBytes, ivBytes) { if (!payload?.length || payload.length % 16) return ''; try { const key = await crypto.subtle.importKey('raw', keyBytes, 'AES-CBC', false, ['decrypt']); const decrypted = new Uint8Array(await crypto.subtle.decrypt({ name:'AES-CBC', iv:ivBytes }, key, payload)); return asciiUrl(decrypted) || asciiUrl(stripPkcs7(decrypted)); } catch { return ''; } }
  async function decodeMainUrl(token, keySeed = '') { if (isHttpUrl(token)) return normalizeUrl(token); const plain = asciiUrl(base64DecodeLoose(token)); if (plain) return normalizeUrl(plain); const data = token?.startsWith('qAAB') && base64DecodeLoose(token), seed = base64DecodeLoose(keySeed); if (!data || !seed) return ''; const digest1 = new Uint8Array(await crypto.subtle.digest('SHA-512', seed.slice(0, 32))), digest2 = new Uint8Array(await crypto.subtle.digest('SHA-512', concat(digest1, hexBytes(QAAB_SALT_HEX)))), key = digest2.slice(0, 16), iv = digest2.slice(16, 32); const attempts = data.length >= 4 && data[0] === 0xa8 && data[1] === 0x00 && data[2] === 0x01 && data[3] === 0x00 ? [{ payload:data.slice(4), key, iv }, { payload:data.slice(4), key:iv, iv:key }, ...(data.length > 36 ? [{ payload:data.slice(36), key, iv:data.slice(20, 36) }, { payload:data.slice(36), key, iv }] : [])] : [{ payload:data, key, iv }]; for (const attempt of attempts) { const url = await decryptUrl(attempt.payload, attempt.key, attempt.iv); if (url) return normalizeUrl(url); } return ''; }
  function findKeySeed(value, depth = 0) { if (depth > 10 || value == null) return ''; if (typeof value === 'string') { const hit = value.match(/(?:^|[?&])key_seed=([^&"'<>\\\s]+)/i) || value.match(/["']key_seed["']\s*:\s*["']([^"']+)/i); return hit ? decodeURIComponent(hit[1]) : ''; } if (typeof value !== 'object') return ''; if (typeof value.key_seed === 'string') return value.key_seed; for (const child of Object.values(value)) { const hit = findKeySeed(child, depth + 1); if (hit) return hit; } return ''; }
  // 与 WeiJunn/doubaoAssistant 保持一致：无水印性由 fallback_api 的 logo_type=unwatermarked
  // 决定，不能仅凭签名 URL 中出现 “watermark” 字样误判。
  async function fallbackMediaInfo(api) { const parsed = new URL(api, location.href); lastFallbackHost = parsed.hostname; parsed.searchParams.set('channel', 'no'); parsed.searchParams.set('codec_type', '8'); parsed.searchParams.set('logo_type', 'unwatermarked'); lastResolveStage = `正在请求无水印接口（${lastFallbackHost}）`; lastResolveError = ''; publishDebug(); const payload = await backgroundJson(parsed.href), info = payload?.video_info || payload?.data?.video_info || payload, data = info?.data || info, entries = data?.video_list && typeof data.video_list === 'object' ? Object.values(data.video_list) : [data]; lastResolveStage = '已收到接口响应，正在选择原始码流'; publishDebug(); const best = entries.filter((entry) => entry && typeof entry === 'object' && (entry.main_url || entry.play_url)).sort((a, b) => Number(b.bitrate || b.real_bitrate || 0) + Number(b.vwidth || b.width || 0) * Number(b.vheight || b.height || 0) - Number(a.bitrate || a.real_bitrate || 0) - Number(a.vwidth || a.width || 0) * Number(a.vheight || a.height || 0))[0]; if (!best) throw new Error(`接口响应中没有 main_url/play_url（根字段：${Object.keys(payload || {}).slice(0, 8).join(',') || '空'}）`); const token=String(best.main_url || best.play_url), keySeed=findKeySeed(payload), url=await decodeMainUrl(token,keySeed); if (!url) throw new Error(`原始码流地址解码失败（${token.startsWith('qAAB') ? 'qAAB' : '非qAAB'}；key_seed ${keySeed ? '存在' : '缺失'}）`); lastResolveStage = '无水印原始流解析完成'; lastResolveError = ''; publishDebug(); return { url, poster:normalizeUrl(data.poster_url || data.poster || info?.poster_url || ''), width:Number(best.vwidth || best.width || data.vwidth || data.width || 0), height:Number(best.vheight || best.height || data.vheight || data.height || 0), duration:Number(best.duration || data.duration || 0), definition:String(best.definition || data.definition || '') }; }
  async function originalUrlFor(vid) { const params = new URLSearchParams({ version_code:'20800', language:'zh-CN', device_platform:'web', aid:'497858', real_aid:'497858', pkg_type:'release_version', device_id:'', pc_version:'2.51.7', region:'', sys_region:'', samantha_web:'1', 'use-olympus-account':'1', web_tab_id:'' }), controller = new AbortController(), timeout = setTimeout(() => controller.abort(), 2800); try { const response = await fetch(`/samantha/media/get_play_info?${params}`, { method:'POST', credentials:'include', signal:controller.signal, headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ key:vid }) }); if (!response.ok) return ''; const payload = await response.json(); return normalizeUrl(payload?.data?.original_media_info?.main_url || ''); } catch { return ''; } finally { clearTimeout(timeout); } }
  async function resolveOriginalMedia(attempts = 12, pause = 750) { scanRenderedMediaData(); const ids = [...videoIds(window._ROUTER_DATA)].reverse(); if (!fallbackApis.size && !ids.length) { lastResolveStage='未捕获 fallback_api 或视频 ID'; publishDebug(); return []; } for (let attempt = 0; attempt < attempts; attempt += 1) { const candidates=[], seenUrls=new Set(); for (const api of [...fallbackApis].reverse()) { try { const media = await fallbackMediaInfo(api); if (media?.url && !seenUrls.has(media.url)) { seenUrls.add(media.url); candidates.push(media); } } catch (error) { lastResolveError=error?.message || String(error); lastResolveStage='无水印接口解析失败'; publishDebug(); } } if (candidates.length) return candidates; for (const vid of ids) { const url = await originalUrlFor(vid); if (url && !seenUrls.has(url)) { lastResolveStage='通过视频 ID 解析完成'; lastResolveError=''; publishDebug(); candidates.push({ url, poster:'', width:0, height:0, duration:0, definition:'' }); } } if (candidates.length) return candidates; if (attempt < attempts - 1) await wait(pause); } return []; }
  async function resolveOriginalUrl(attempts = 12, pause = 750) { const candidates = await resolveOriginalMedia(attempts, pause); return candidates[0]?.url || ''; }
  function observeHistoryResponse(response, request) { observedEndpoints.add(String(request).slice(0, 180)); publishDebug(); response.clone().text().then((text) => { collectFallbackApis(null, text); try { collectFallbackApis(JSON.parse(text), text); } catch {} }).catch(() => {}); }
  function streamCompletionResponse(response, request) { observedEndpoints.add(String(request).slice(0, 180)); publishDebug(); if (!response.body || typeof response.body.getReader !== 'function') return response; const reader = response.body.getReader(), decoder = new TextDecoder(), headers = response.headers; const stream = new ReadableStream({ async start(controller) { let buffer=''; try { while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream:true }); const lines = buffer.split('\n'); buffer = lines.pop() || ''; for (const line of lines) { if (!line.startsWith('data: ')) continue; const raw = line.slice(6); if (!/fallback_api|creation_block|original_media_info/i.test(raw)) continue; try { collectFallbackApis(JSON.parse(raw), raw); } catch { collectFallbackApis(null, raw); } } controller.enqueue(value); } const rest = decoder.decode(); if (rest) controller.enqueue(new TextEncoder().encode(rest)); controller.close(); } catch (error) { controller.error(error); } } }); return new Response(stream, { headers, status:response.status, statusText:response.statusText }); }
  const nativeFetch = window.fetch;
  window.fetch = async function (...args) { const response = await nativeFetch.apply(this, args); const request = typeof args[0] === 'string' ? args[0] : args[0]?.url || ''; if (/\/im\/chain\/single/.test(request)) { observeHistoryResponse(response, request); return response; } if (/\/chat\/completion/.test(request)) return streamCompletionResponse(response, request); return response; };
  const nativeOpen = XMLHttpRequest.prototype.open, nativeSend = XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.open = function (method, url, ...args) { this.__doubaoStudioUrl = url; return nativeOpen.call(this, method, url, ...args); };
  XMLHttpRequest.prototype.send = function (...args) { this.addEventListener('load', () => { const request=String(this.__doubaoStudioUrl || ''); if (!/\/im\/chain\/single/.test(request)) return; observedEndpoints.add(request.slice(0, 180)); publishDebug(); const text=this.responseText || ''; collectFallbackApis(null, text); try { collectFallbackApis(JSON.parse(text), text); } catch {} }); return nativeSend.apply(this, args); };
  window.addEventListener('message', async (event) => { if (event.source !== window) return; if (event.data?.type === MESSAGE) { try { const media = (await resolveOriginalMedia())[0] || null; window.postMessage({ type:RESULT, requestId:event.data.requestId, url:media?.url || null, media, error:lastResolveError || null }, location.origin); } catch (error) { window.postMessage({ type:RESULT, requestId:event.data.requestId, url:null, media:null, error:error?.message || '媒体解析失败' }, location.origin); } return; } if (event.data?.type === STATUS_REQUEST) { try { const candidates = await resolveOriginalMedia(2, 350), diagnostic=candidates.length ? null : `${lastResolveStage}${lastFallbackHost ? `（${lastFallbackHost}）` : ''}${lastResolveError ? `：${lastResolveError}` : ''}`; window.postMessage({ type:STATUS_RESULT, requestId:event.data.requestId, url:candidates[0]?.url || null, candidates, fallbackCount:fallbackApis.size, observedCount:observedEndpoints.size, diagnostic, error:candidates.length ? null : diagnostic }, location.origin); } catch (error) { window.postMessage({ type:STATUS_RESULT, requestId:event.data.requestId, url:null, candidates:[], fallbackCount:fallbackApis.size, observedCount:observedEndpoints.size, diagnostic:error?.message || '媒体检测失败', error:error?.message || '媒体检测失败' }, location.origin); } } });
})();
}
